# Generated by Django 2.1.5 on 2019-01-28 01:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isExpense', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('transactionDate', models.DateField(default=datetime.datetime(2019, 1, 28, 8, 24, 23, 130896))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyCirculation.Category')),
            ],
        ),
    ]
