# Generated by Django 2.1.5 on 2019-01-28 01:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moneyCirculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='transactionDate',
            field=models.DateField(default=datetime.datetime(2019, 1, 28, 1, 29, 43, 11700, tzinfo=utc)),
        ),
    ]
